'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useAuth } from '@/components/auth/AuthProvider';
import { supabase } from '@/lib/supabase/client';

export default function CreatePool() {
  const { user } = useAuth();
  const [name, setName] = useState('');
  const [entryFee, setEntryFee] = useState('');
  const [maxPlayers, setMaxPlayers] = useState('');
  const [isPrivate, setIsPrivate] = useState(true);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const router = useRouter();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    if (!user) {
      setError('You must be logged in to create a pool');
      setLoading(false);
      return;
    }

    try {
      // Create the pool - join_code will be auto-generated by trigger
      const { data: pool, error: poolError } = await supabase
        .from('pools')
        .insert({
          name,
          creator_id: user.id,
          entry_fee: entryFee ? parseFloat(entryFee) : 0,
          max_players: maxPlayers ? parseInt(maxPlayers) : null,
          is_private: isPrivate,
          tournament_year: 2025, // Current tournament year
          status: 'open'
        })
        .select()
        .single();

      if (poolError) throw poolError;

      // Auto-join the creator to their own pool
      const { error: playerError } = await supabase
        .from('pool_players')
        .insert({
          pool_id: pool.id,
          user_id: user.id,
          display_name: user.user_metadata?.display_name || user.email?.split('@')[0] || 'Player',
        });

      if (playerError) throw playerError;

      // Redirect to the pool page
      router.push(`/pools/${pool.id}`);
    } catch (err: any) {
      setError(err.message || 'Failed to create pool');
      setLoading(false);
    }
  };

  // Redirect to login if not authenticated
  if (!user) {
    router.push('/auth/login');
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-xl">Redirecting to login...</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white shadow-sm border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between py-4">
            <h1 className="text-2xl font-bold text-gray-900">Create Pool</h1>
            <Link
              href="/dashboard"
              className="text-blue-600 hover:text-blue-700 font-medium"
            >
              ← Back to Dashboard
            </Link>
          </div>
        </div>
      </header>

      <main className="max-w-2xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="bg-white rounded-lg shadow-md p-6">
          {error && (
            <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg mb-6">
              {error}
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-6">
            <div>
              <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-2">
                Pool Name *
              </label>
              <input
                id="name"
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                required
                maxLength={100}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                placeholder="e.g., Office March Madness 2025"
              />
            </div>

            <div>
              <label htmlFor="entryFee" className="block text-sm font-medium text-gray-700 mb-2">
                Entry Fee (optional)
              </label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <span className="text-gray-500 text-sm">$</span>
                </div>
                <input
                  id="entryFee"
                  type="number"
                  step="0.01"
                  min="0"
                  max="999.99"
                  value={entryFee}
                  onChange={(e) => setEntryFee(e.target.value)}
                  className="w-full pl-7 pr-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder="0.00"
                />
              </div>
              <p className="text-sm text-gray-500 mt-1">Leave blank for free pools</p>
            </div>

            <div>
              <label htmlFor="maxPlayers" className="block text-sm font-medium text-gray-700 mb-2">
                Max Players (optional)
              </label>
              <input
                id="maxPlayers"
                type="number"
                min="2"
                max="1000"
                value={maxPlayers}
                onChange={(e) => setMaxPlayers(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                placeholder="No limit"
              />
              <p className="text-sm text-gray-500 mt-1">Leave blank for unlimited players</p>
            </div>

            <div>
              <label className="flex items-center space-x-3">
                <input
                  type="checkbox"
                  checked={isPrivate}
                  onChange={(e) => setIsPrivate(e.target.checked)}
                  className="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
                />
                <span className="text-sm font-medium text-gray-700">
                  Private Pool
                </span>
              </label>
              <p className="text-sm text-gray-500 mt-1">
                Private pools require a join code. Public pools can be discovered by anyone.
              </p>
            </div>

            <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
              <h3 className="font-medium text-blue-900 mb-2">Survivor Pool Rules:</h3>
              <ul className="text-sm text-blue-800 space-y-1">
                <li>• Pick one team per tournament day to win their game</li>
                <li>• Each team can only be picked once throughout the tournament</li>
                <li>• Wrong pick or missed deadline = elimination</li>
                <li>• Picks must be submitted 30 minutes before first tip-off each day</li>
                <li>• Last player standing wins the pool</li>
              </ul>
            </div>

            <button
              type="submit"
              disabled={loading || !name.trim()}
              className="w-full bg-blue-600 hover:bg-blue-700 disabled:bg-blue-400 text-white font-medium py-3 px-4 rounded-md transition-colors"
            >
              {loading ? 'Creating Pool...' : 'Create Pool'}
            </button>
          </form>
        </div>
      </main>
    </div>
  );
}